# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

GMAIL_USERNAME: hakicebi
GMAIL_PASSWORD: 
SENDGRID_USERNAME: app21939997@heroku.com
SENDGRID_PASSWORD: 8eib1nua

MAILGUN_SMTP_PORT: 587
MAILGUN_SMTP_SERVER: 'smtp.mailgun.org'
MAILGUN_SMTP_LOGIN: 'postmaster@app21939997.mailgun.org'
MAILGUN_SMTP_PASSWORD: '5wrxjq-uo2o8'